name: Build and Deploy Azure Function

on:
  push:
    branches:
      - main  # o la rama que uses para deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # O la versión que uses

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --no-build

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: 'estebansFunctions'   # Tu nombre de Azure Function
          package: './publish'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
